### ISSUE TITLE
Problemas para generar una especificación RPCGen en la segunda parte del programa

### ISSUE THREAD

**Issue by SeanBurger72** [Innova4DLab/RPCGen#1]
Este es mi código y tengo problemas para generar el Documento porque me marca un error.
Gracias de Antemano

struct intpair {
int a;
int b;
};
program AgregaBusca_PROG {
version AgregaBUsca_VERS {
time_t t = time(NULL);
struct tm tm = *localtime(&t);

printf("now: %d-%d-%d %d:%d:%d\n", tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec);

time_t t = time(NULL);
struct tm tm = *localtime(&t);

printf("now: %d-%d-%d %d:%d:%d\n", tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec);
#include <stdlib.h>
 #include <string.h>

 char buff[1000];
 char *s;

 s = strstr(buff, "hassasin");      // search for string "hassasin" in buff
 if (s != NULL)                     // if succesfull then s now points at "hassasin"
 {
     printf("Found string at index = %d\n", s - buff);
 }                                  // index of "hassasin" in buff can be found by pointer subtraction
 else
 {
     printf("String not found\n");  // `strstr` returns NULL if search string not found
 }

}}

**Comment by FranciscoGutierrez** [comment]
Precisamente, qué error aparece en la consola?

**Comment by FranciscoGutierrez** [comment]
Para abrir un archivo y agregar texto puedes usar el siguiente código:

```cpp
FILE *f = fopen("file.txt", "a+");
if (f == NULL) {
    printf("Error opening file!\n");
    exit(1);
}
/* print some text */
const char *text = "Write this to the file";
fprintf(f, "Some text: %s\n", text);
```

**Comment by SeanBurger72** [comment]
Pues me menciona que falta un parentesis en la linea de tiempo
time_t t = time(Null)


2015-02-17 13:42 GMT-06:00 Francisco G. <notifications@github.com>:

**Comment by FranciscoGutierrez** [comment]
Para el servidor, específicamente en la función agregar, deberías tener algo mas o menos así:
``` c
#include "add.h"
#include <time.h>
#include <stdlib.h>
#include <string.h>

char **
add_1_svc(char **argp, struct svc_req *rqstp) {
	static char * result;
	/*
	 * insert server code here
	 */
	time_t timeres = time(NULL);
	FILE *f = fopen("file.txt", "a+"); 
	if (f == NULL) {
    printf("Error opening file!\n");
    exit(1);
	}
	char * time = asctime(localtime(&timeres));
	fprintf(f, "%s %s", *argp, time);
	printf("Server Added:%s %s", *argp, time);
	fclose(f);
	asprintf(&result, "%s %s", *argp, time);
	return &result;
}
```

**Comment by SeanBurger72** [comment]
Hola Francisco oye puedes decirle a la Dra.Ofelia que revise su correo
porque ya le envie el software y el reporte a su correo. El detalle esta en
que no puedo subirlo al portafolio
saludos y gracias de antemano

2015-02-17 14:06 GMT-06:00 Francisco G. <notifications@github.com>:
